return lowerkeys({
  aat_dead = {
            description = "dead anti air tower :(",
            damage = 500,
            object = "dead/AATDED.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 72,
            metal = 72,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			featureDead = "aat_heap",
			collisionVolumeOffsets    =  "0 25 0",
			collisionVolumeScales     =  "25 88 25",
			collisionvolumetype = "box",
},
aat_heap = {
            description = "very dead anti air tower :(",
            damage = 100,
            object = "dead/Pieces_Small.s3o",
            footprintz = 2,
            footprintx = 2,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 18,
            metal = 18,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "35 5 35",
			collisionvolumetype = "box",
},
})