return lowerkeys({
  archer_dead = {
            description = "dead archer :(",
            damage = 356,
            object = "dead/ArcherDED.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 80,
            metal = 80,
            hitdensity = 150,
			featureDead  = "archer_heap",
            world = "All Worlds",
            category = "dedunit",
			collisionVolumeOffsets    =  "0 0 0",
			collisionVolumeScales     = "46 28 71",
			collisionvolumetype = "box",
},
archer_heap = {
            description = "very dead archer :(",
            damage = 86.5,
            object = "dead/Pieces_Big.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 20,
            metal = 20,
            hitdensity = 150,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "45 7 45",
			collisionvolumetype = "box",
},
})
