return lowerkeys({
  cleaver_dead = {
            description = "dead cleaver :(",
            damage = 500,
            object = "dead/CleaverDED.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 94,
            metal = 94,
            hitdensity = 150,
			featureDead  = "cleaver_heap",
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 -5 0",
			collisionVolumeScales =  "31 32 43",
			collisionvolumetype = "box",
},
cleaver_heap = {
            description = "very dead cleaver :(",
            damage = 100,
            object = "dead/Pieces_Big.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 23.5,
            metal = 23.5,
            hitdensity = 150,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "45 7 45",
			collisionvolumetype = "box",
},
})
