return lowerkeys({
  crane_dead = {
            description = "dead crane :(",
            damage = 225,
            object = "dead/CraneDED.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 50,
            metal = 50,
            hitdensity = 150,
			featureDead  = "crane_heap",
            world = "All Worlds",
            category = "dedunit",
			collisionVolumeOffsets    =  "0 -4 0",
			collisionVolumeScales     =  "31 16 44",
			collisionvolumetype = "box",
},
crane_heap = {
            description = "very dead crane :(",
            damage = 55,
            object = "dead/Pieces_Big.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 12.5,
            metal = 12.5,
            hitdensity = 150,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionVolumeScales     =  "48 13 51",
			collisionvolumetype = "box",
},
})
