return lowerkeys({
  extractor_dead = {
            description = "dead extractor :(",
            damage = 200,
            object = "dead/ExtractorDED.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 24,
            metal = 24,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			featureDead = "extractor_heap",
			collisionVolumeOffsets    =  "0 -35 0",
			collisionVolumeScales     =  "31 98 30",
			collisionvolumetype = "box",
},
extractor_heap = {
            description = "very dead extractor :(",
            damage = 32,
            object = "dead/Pieces_Small.s3o",
            footprintz = 2,
            footprintx = 2,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 6,
            metal = 6,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "35 5 35",
			collisionvolumetype = "box",
},
})