return lowerkeys({
  fusionreactor_dead = {
            description = "dead fusion reactor :(",
            damage = 1250,
            object = "dead/Fusion ReactorDED.s3o",
            footprintz = 7,
            footprintx = 5,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 350,
            metal = 350,
            hitdensity = 300,
            world = "All Worlds",
            category = "dedunit",
			featureDead = "fusionreactor_heap",
			collisionVolumeOffsets    =  "0 10 0",
			collisionVolumeScales     =  "65 101 102",
			collisionvolumetype = "box",
},
fusionreactor_heap = {
            description = "very dead fusion reactor :(",
            damage = 250,
            object = "dead/Pieces_ExBig.s3o",
            footprintz = 4,
            footprintx = 4,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 87.5,
            metal = 87.5,
            hitdensity = 200,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "60 8 60",
			collisionvolumetype = "box",
},
})