return lowerkeys({
  geothermalplasmacannon_dead = {
            description = "dead geothermal plasma cannon D:",
            damage = 1750,
            object = "dead/Geothermal Plasma CannonDED.s3o",
            footprintz = 6,
            footprintx = 6,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 800,
            metal = 800,
            hitdensity = 300,
            world = "All Worlds",
            category = "dedunit",
			featureDead = "geothermalplasmacannon_heap",
			collisionVolumeOffsets    =  "0 10 0",
			collisionVolumeScales     =  "60 56 60",
			collisionvolumetype = "box",
},
geothermalplasmacannon_heap = {
            description = "very dead geothermal plasma cannon D:",
            damage = 250,
            object = "dead/Pieces_ExBig.s3o",
            footprintz = 4,
            footprintx = 4,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 200,
            metal = 200,
            hitdensity = 200,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "60 8 60",
			collisionvolumetype = "box",
},
})