return lowerkeys({
  groundfactory_dead = {
            description = "dead ground factory :(",
            damage = 1750,
            object = "dead/FactoryDED.s3o",
            footprintz = 11,
            footprintx = 8,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 300,
            metal = 300,
            hitdensity = 300,
            world = "All Worlds",
            category = "dedunit",
			featureDead = "groundfactory_heap",
			collisionVolumeOffsets    =  "0 0 -7.5",
			collisionVolumeScales     =  "119 99 174",
			collisionvolumetype = "box",
},
groundfactory_heap = {
            description = "very dead ground factory  :(",
            damage = 350,
            object = "dead/Pieces_ExBig.s3o",
            footprintz = 4,
            footprintx = 4,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 75,
            metal = 75,
            hitdensity = 200,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "60 8 60",
			collisionvolumetype = "box",
},
})