return lowerkeys({
  harpy_dead = {
            description = "dead harpy :(",
            damage = 287.5,
            object = "dead/HarpyDED.s3o", --"HunterT.s3o"
            footprintz = 2,
            footprintx = 2,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 74,
            metal = 74,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			featureDead = "harpy_heap",
			collisionvolumeoffsets = "0 0 0",
			collisionVolumeScales     =  "17 14 40",
			collisionvolumetype = "box",
},
harpy_heap = {
            description = "very dead harpy :(",
            damage = 57.5,
            object = "dead/Pieces_Small.s3o",
            footprintz = 2,
            footprintx = 2,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 18.5,
            metal = 18.5,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "35 5 35",
			collisionvolumetype = "box",
},
})