return lowerkeys({
  llt_dead = {
            description = "dead light laser tower :(",
            damage = 375,
            object = "dead/LLTDED.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 40,
            metal = 40,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			featureDead = "llt_heap",
			collisionVolumeOffsets    =  "0 25 0",
			collisionVolumeScales     =  "25 83 25",
			collisionvolumetype = "box",
},
llt_heap = {
            description = "very dead light laser tower :(",
            damage = 75,
            object = "dead/Pieces_Small.s3o",
            footprintz = 2,
            footprintx = 2,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 10,
            metal = 10,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "35 5 35",
			collisionvolumetype = "box",
},
})