return lowerkeys({
  mangonel_dead = {
            description = "dead mangonel :(",
            damage = 337.5,
            object = "dead/MangonelDED.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 170,
            metal = 170,
            hitdensity = 150,
			featureDead  = "mangonel_heap",
            world = "All Worlds",
            category = "dedunit",
			collisionVolumeOffsets    =  "0 -4 -5",
			collisionVolumeScales     =  "31.5 35 55",
			collisionvolumetype = "box",
},
mangonel_heap = {
            description = "very dead mangonel :(",
            damage = 67.5,
            object = "dead/Pieces_Big.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 42.5,
            metal = 42.5,
            hitdensity = 150,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "45 7 45",
			collisionvolumetype = "box",
},
})
