return lowerkeys({
  navalconstructor_dead = {
            description = "dead naval constructor :(",
            damage = 287.5,
            object = "dead/Naval ConstructorDED.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 50,
            metal = 50,
            hitdensity = 150,
			featureDead  = "navalconstructor_heap",
            world = "All Worlds",
            category = "dedunit",
			collisionVolumeOffsets    =  "0 0 0",
			collisionVolumeScales     =  "41 26 66",
			collisionvolumetype = "box",
},
navalconstructor_heap = {
            description = "very dead naval constructor :(",
            damage = 57.5,
            object = "dead/Pieces_Big.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 12.5,
            metal = 12.5,
            hitdensity = 150,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "45 7 45",
			collisionvolumetype = "box",
},
})
