return lowerkeys({
  panther_dead = {
            description = "dead panther :(",
            damage = 700,
            object = "dead/PantherDED.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 120,
            metal = 120,
            hitdensity = 150,
			featureDead  = "panther_heap",
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 -5 0",
		 collisionVolumeScales     =  "32 32 43",
			collisionvolumetype = "box",
},
panther_heap = {
            description = "very dead panther :(",
            damage = 140,
            object = "dead/Pieces_Big.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 30,
            metal = 30,
            hitdensity = 150,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "45 7 45",
			collisionvolumetype = "box",
},
})
