return lowerkeys({
  stunburst_dead = {
            description = "dead stunburst :(",
            damage = 77.5,
            object = "dead/StunburstDED.s3o",
            footprintz = 2,
            footprintx = 2,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 16,
            metal = 16,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			featureDead = "stunburst_heap",
			collisionvolumeoffsets = "0 -5 0",
		collisionVolumeScales     =  "17 24 25",
			collisionvolumetype = "box",
},
stunburst_heap = {
            description = "very dead stunburst :(",
            damage = 15.5,
            object = "dead/Pieces_Small.s3o",
            footprintz = 2,
            footprintx = 2,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 4,
            metal = 4,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "35 5 35",
			collisionvolumetype = "box",
},
})