return lowerkeys({
  tp_dead = {
            description = "dead torpedo platform :(",
            damage = 500,
            object = "dead/TPDED.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 74,
            metal = 74,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			featureDead = "tp_heap",
			collisionVolumeOffsets    =  "0 0 0",
			collisionVolumeScales     =  "39 11 35",
			collisionvolumetype = "box",
},
tp_heap = {
            description = "very dead torpedo platform :(",
            damage = 100,
            object = "dead/Pieces_Small.s3o",
            footprintz = 2,
            footprintx = 2,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 18.5,
            metal = 18.5,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "35 5 35",
			collisionvolumetype = "box",
},
})