--llt
--cleaver
--hlt
--lurker
--commander
--panther
--shatterer
--commander2
--hawk
--harpy
--gazer
--stingray
--archer
return {
--llt
  ["llthit"] = {
  usedefaultexplosions = false,
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 0,
      flashalpha         = 0.8,
      flashsize          = 8,
      ttl                = 3,
      color = {
        [1]  = 0.8,
        [2]  = 0.8,
        [3]  = 0.4,
      },
    },
   spark = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      unit               = 1,
	  water              = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[0.8 0.8 0.4 0.01   0.7 0.7 0.35 0.01   0.4 0.4 0.2 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 40,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.45, 0]],
        numparticles       = 6,
        particlelife       = 6,
        particlelifespread = 2,
        particlesize       = 6,
        particlesizespread = 2,
        particlespeed      = 4,
        particlespeedspread = 12, --4
        pos                = [[0, 1, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[simplespark]],
      },
    },
},
--cleaver
["cleaverhit"] = {
  usedefaultexplosions = false,
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 0,
      flashalpha         = 0.8,
      flashsize          = 8,
      ttl                = 3,
      color = {
        [1]  = 0.6,
        [2]  = 0.6,
        [3]  = 0.3,
      },
    },
   spark = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      unit               = 1,
	  water              = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[0.6 0.6 0.3 0.01   0.5 0.5 0.25 0.01   0.3 0.3 0.15 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 40,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.45, 0]],
        numparticles       = 9,
        particlelife       = 7,
        particlelifespread = 3,
        particlesize       = 6.5,
        particlesizespread = 3,
        particlespeed      = 4,
        particlespeedspread = 16, --4
        pos                = [[0, 1, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[simplespark]],
      },
    },
},
--hlt
["hlthit"] = {
  usedefaultexplosions = false,
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 0,
      flashalpha         = 0.8,
      flashsize          = 12,
      ttl                = 5,
      color = {
        [1]  = 0.3,
        [2]  = 0.9,
        [3]  = 0.6,
      },
    },
   spark = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      unit               = 1,
	  water              = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[0.3 0.9 0.6 0.01   0.22 0.8 0.4 0.01   0.15 0.7 0.2 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 40,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.25, 0]],
        numparticles       = 16,
        particlelife       = 30,
        particlelifespread = 3,
        particlesize       = 8,
        particlesizespread = 4,
        particlespeed      = 5,
        particlespeedspread = 15, --4
        pos                = [[0, 1, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[simplespark]],
      },
    },
	sphere = {
            air                = true,
            class              = [[CSpherePartSpawner]],
            count              = 1,
            ground             = true,
            water              = true,
            properties = {
                alpha              = 0.5,
                alwaysvisible      = true,
                color              = [[0.3,0.9,0.6]],
                expansionspeed     = 4.5,
                ttl                = 12,
            },
        },
},
--lurker
["lurkerhit"] = {
  usedefaultexplosions = false,
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 0,
      flashalpha         = 0.8,
      flashsize          = 12,
      ttl                = 9.5,
      color = {
        [1]  = 1,
        [2]  = 0.2,
        [3]  = 0.2,
      },
    },
   spark = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      unit               = 1,
	  water              = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[1 0.2 0.2 0.01   0.8 0.15 0.15 0.01   0.6 0.1 0.1 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 40,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.25, 0]],
        numparticles       = 16,
        particlelife       = 30,
        particlelifespread = 3,
        particlesize       = 8,
        particlesizespread = 4,
        particlespeed      = 5,
        particlespeedspread = 15, --4
        pos                = [[0, 1, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[simplespark]],
      },
    },
	sphere = {
            air                = true,
            class              = [[CSpherePartSpawner]],
            count              = 1,
            ground             = true,
            water              = true,
            properties = {
                alpha              = 0.5,
                alwaysvisible      = true,
                color              = [[1,0.2,0.2]],
                expansionspeed     = 3,
                ttl                = 10,
            },
        },
},
--commander
["commanderhit"] = {
  usedefaultexplosions = false,
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 0,
      flashalpha         = 0.8,
      flashsize          = 7,
      ttl                = 5,
      color = {
        [1]  = 0.8,
        [2]  = 0.4,
        [3]  = 0.4,
      },
    },
   spark = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      unit               = 1,
	  water              = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[0.8 0.4 0.4 0.01   0.7 0.3 0.3 0.01   0.55 0.15 0.15 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 40,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.6, 0]],
        numparticles       = 4,
        particlelife       = 18,
        particlelifespread = 3,
        particlesize       = 6,
        particlesizespread = 4,
        particlespeed      = 5,
        particlespeedspread = 15, --4
        pos                = [[0, 1, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[simplespark]],
      },
    },
	sphere = {
            air                = true,
            class              = [[CSpherePartSpawner]],
            count              = 1,
            ground             = true,
            water              = true,
            properties = {
                alpha              = 0.5,
                alwaysvisible      = true,
                color              = [[0.8,0.4,0.4]],
                expansionspeed     = 4,
                ttl                = 6,
            },
        },
},
--panther
["pantherhit"] = {
  usedefaultexplosions = false,
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 0,
      flashalpha         = 0.8,
      flashsize          = 7,
      ttl                = 5,
      color = {
        [1]  = 0.35,
        [2]  = 0.6,
        [3]  = 1,
      },
    },
   bluespark = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      unit               = 1,
	  water              = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[0.35 0.6 1 0.01   0.275 0.7 0.9 0.01   0.2 0.3 0.8 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 40,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.6, 0]],
        numparticles       = 5,
        particlelife       = 18,
        particlelifespread = 3,
        particlesize       = 6,
        particlesizespread = 4,
        particlespeed      = 5,
        particlespeedspread = 15, --4
        pos                = [[0, 1, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[simplespark]],
      },
    },
	yellowspark = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      unit               = 1,
	  water              = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[0.8 0.8 0.4 0.01   0.65 0.65 0.3 0.01   0.5 0.5 0.2 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 40,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.6, 0]],
        numparticles       = 5,
        particlelife       = 18,
        particlelifespread = 3,
        particlesize       = 6,
        particlesizespread = 4,
        particlespeed      = 5,
        particlespeedspread = 15, --4
        pos                = [[0, 1, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[simplespark]],
      },
    },
	sphere = {
            air                = true,
            class              = [[CSpherePartSpawner]],
            count              = 1,
            ground             = true,
            water              = true,
            properties = {
                alpha              = 0.5,
                alwaysvisible      = true,
                color              = [[0.35,0.6,1]],
                expansionspeed     = 4.25,
                ttl                = 9,
            },
        },
},
--shatterer
["shattererhit"] = {
  usedefaultexplosions = false,
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 4,
      flashalpha         = 0.8,
      flashsize          = 34,
      ttl                = 14,
      color = {
        [1]  = 0.35,
        [2]  = 0.6,
        [3]  = 1,
      },
    },
   bluespark = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      unit               = 1,
	  water              = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[0.35 0.6 1 0.01   0.275 0.7 0.9 0.01   0.2 0.3 0.8 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 40,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.6, 0]],
        numparticles       = 8,
        particlelife       = 22,
        particlelifespread = 4,
        particlesize       = 7,
        particlesizespread = 4.5,
        particlespeed      = 5,
        particlespeedspread = 15, --4
        pos                = [[0, 1, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[simplespark]],
      },
    },
	yellowspark = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      unit               = 1,
	  water              = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[0.8 0.8 0.4 0.01   0.65 0.65 0.3 0.01   0.5 0.5 0.2 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 40,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.6, 0]],
        numparticles       = 8,
        particlelife       = 22,
        particlelifespread = 4,
        particlesize       = 7,
        particlesizespread = 4.5,
        particlespeed      = 5,
        particlespeedspread = 15, --4
        pos                = [[0, 1, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[simplespark]],
      },
    },
	sphere = {
            air                = true,
            class              = [[CSpherePartSpawner]],
            count              = 1,
            ground             = true,
            water              = true,
            properties = {
                alpha              = 0.5,
                alwaysvisible      = true,
                color              = [[0.35,0.6,1]],
                expansionspeed     = 6.2,
                ttl                = 16,
            },
        },
},
--commander2
["commanderhit2"] = {
  usedefaultexplosions = false,
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 3,
      flashalpha         = 0.8,
      flashsize          = 36,
      ttl                = 10,
      color = {
        [1]  = 1,
        [2]  = 0.6,
        [3]  = 0.25,
      },
    },
   spark = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      unit               = 1,
	  water              = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[1 0.6 0.25 0.01   0.8 0.5 0.2 0.01   0.6 0.35 0.15 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 40,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.6, 0]],
        numparticles       = 7,
        particlelife       = 24,
        particlelifespread = 4.5,
        particlesize       = 6,
        particlesizespread = 4.5,
        particlespeed      = 5,
        particlespeedspread = 18, --4
        pos                = [[0, 1, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[simplespark]],
      },
    },
	sphere = {
            air                = true,
            class              = [[CSpherePartSpawner]],
            count              = 1,
            ground             = true,
            water              = true,
            properties = {
                alpha              = 0.5,
                alwaysvisible      = true,
                color              = [[1,0.6,0.25]],
                expansionspeed     = 5,
                ttl                = 16,
            },
        },
},
--hawk
["hawkhit"] = {
  usedefaultexplosions = false,
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 0,
      flashalpha         = 0.8,
      flashsize          = 7,
      ttl                = 5,
	  ground             = true,
	  air				 = false,
      color = {
        [1]  = 0.8,
        [2]  = 0.8,
        [3]  = 0.4,
      },
    },
   spark = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      unit               = 1,
	  water              = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[0.8 0.8 0.4 0.01   0.7 0.7 0.3 0.01   0.55 0.55 0.15 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 40,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.6, 0]],
        numparticles       = 5,
        particlelife       = 13,
        particlelifespread = 2,
        particlesize       = 4,
        particlesizespread = 2,
        particlespeed      = 4,
        particlespeedspread = 18, --4
        pos                = [[0, 1, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[simplespark]],
      },
    },
	sphere = {
            air                = true,
            class              = [[CSpherePartSpawner]],
            count              = 1,
            ground             = true,
            water              = true,
            properties = {
                alpha              = 0.5,
                alwaysvisible      = true,
                color              = [[0.8,0.8,0.4]],
                expansionspeed     = 3,
                ttl                = 8,
            },
        },
},
--harpy
["harpyhit"] = {
  usedefaultexplosions = false,
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 1,
      flashalpha         = 0.8,
      flashsize          = 12,
      ttl                = 8.5,
	  --ground             = true,
	  --air				 = false,
      color = {
        [1]  = 0.8,
        [2]  = 0.8,
        [3]  = 0.4,
      },
    },
   spark = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      unit               = 1,
	  water              = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[0.8 0.8 0.4 0.01   0.7 0.7 0.3 0.01   0.55 0.55 0.15 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 40,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.6, 0]],
        numparticles       = 6,
        particlelife       = 14,
        particlelifespread = 2.5,
        particlesize       = 4.5,
        particlesizespread = 2.5,
        particlespeed      = 5,
        particlespeedspread = 20,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[simplespark]],
      },
    },
	sphere = {
            air                = true,
            class              = [[CSpherePartSpawner]],
            count              = 1,
            ground             = true,
            water              = true,
            properties = {
                alpha              = 0.5,
                alwaysvisible      = true,
                color              = [[0.8,0.8,0.4]],
                expansionspeed     = 3,
                ttl                = 12,
            },
        },
},
--gazer
["gazerhit"] = {
  usedefaultexplosions = false,
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 0,
      flashalpha         = 0.8,
      flashsize          = 13,
      ttl                = 4,
      color = {
        [1]  = 0.7,
        [2]  = 0,
        [3]  = 1,
      },
    },
   spark = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      unit               = 1,
	  water              = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[0.7 0 1 0.01   0.5 0 0.75 0.01   0.35 0 0.6 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 40,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.45, 0]],
        numparticles       = 9,
        particlelife       = 7,
        particlelifespread = 3,
        particlesize       = 6.5,
        particlesizespread = 3,
        particlespeed      = 4,
        particlespeedspread = 16, --4
        pos                = [[0, 1, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[simplespark]],
      },
    },
},
--stingray
["stingrayhit"] = {
  usedefaultexplosions = false,
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 0,
      flashalpha         = 0.8,
      flashsize          = 6,
      ttl                = 6,
      color = {
        [1]  = 0.35,
        [2]  = 0.6,
        [3]  = 1,
      },
    },
   bluespark = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      unit               = 1,
	  water              = true,
	  underwater         = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[0.35 0.6 1 0.01   0.275 0.7 0.9 0.01   0.2 0.3 0.8 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 40,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.6, 0]],
        numparticles       = 3,
        particlelife       = 12,
        particlelifespread = 2.5,
        particlesize       = 5,
        particlesizespread = 3,
        particlespeed      = 5,
        particlespeedspread = 15, --4
        pos                = [[0, 1, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[simplespark]],
      },
    },
	yellowspark = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      unit               = 1,
	  water              = true,
	  underwater         = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[0.8 0.8 0.4 0.01   0.65 0.65 0.3 0.01   0.5 0.5 0.2 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 40,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.6, 0]],
        numparticles       = 3,
        particlelife       = 12,
        particlelifespread = 2.5,
        particlesize       = 5,
        particlesizespread = 3,
        particlespeed      = 5,
        particlespeedspread = 15, --4
        pos                = [[0, 1, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[simplespark]],
      },
    },
	sphere = {
            air                = true,
            class              = [[CSpherePartSpawner]],
            count              = 1,
            ground             = true,
            water              = true,
			underwater         = true,
            properties = {
                alpha              = 0.5,
                alwaysvisible      = true,
                color              = [[0.35,0.6,1]],
                expansionspeed     = 2.5,
                ttl                = 9,
            },
        },
},
--archer
["archerhit"] = {
  usedefaultexplosions = false,
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 2,
      flashalpha         = 0.8,
      flashsize          = 12,
      ttl                = 8,
      color = {
        [1]  = 0.8,
        [2]  = 0.6,
        [3]  = 0.4,
      },
    },
   spark = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      unit               = 1,
	  water              = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[0.8 0.6 0.4 0.01   0.7 0.45 0.3 0.01   0.5 0.35 0.15 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 40,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.6, 0]],
        numparticles       = 7,
        particlelife       = 20,
        particlelifespread = 4,
        particlesize       = 5,
        particlesizespread = 5,
        particlespeed      = 5,
        particlespeedspread = 15,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[simplespark]],
      },
    },
	sphere = {
            air                = true,
            class              = [[CSpherePartSpawner]],
            count              = 1,
            ground             = true,
            water              = true,
			underwater         = true,
            properties = {
                alpha              = 0.5,
                alwaysvisible      = true,
                color              = [[0.8,0.6,0.4]],
                expansionspeed     = 4,
                ttl                = 5,
            },
        },
	},
}