return lowerkeys({
  commander_dead = {
            description = "dead commander :(",
            damage = 1875,
            object = "dead/CommanderDED.s3o",
            footprintz = 4,
            footprintx = 4,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 1000,
            metal = 1000,
            hitdensity = 150,
			featureDead  = "commander_heap",
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 -5 0",
			collisionVolumeScales =  "54 44 60",
			collisionvolumetype = "box",
},
commander_heap = {
            description = "very dead commander :(",
            damage = 375,
            object = "dead/Pieces_Big.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 100,
            metal = 100,
            hitdensity = 150,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "45 7 45",
			collisionvolumetype = "box",
},
})
