return lowerkeys({
  constructor_dead = {
            description = "dead constructor :(",
            damage = 250,
            object = "dead/ConstructorDED.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 32,
            metal = 32,
            hitdensity = 150,
			featureDead  = "constructor_heap",
            world = "All Worlds",
            category = "dedunit",
			collisionVolumeOffsets    =  "0 -4 -2",
			collisionVolumeScales     =  "29 27 34",
			collisionvolumetype = "box",
},
constructor_heap = {
            description = "very dead constructor :(",
            damage = 50,
            object = "dead/Pieces_Big.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 8,
            metal = 8,
            hitdensity = 150,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "45 7 45",
			collisionvolumetype = "box",
},
})
