return lowerkeys({
  flow_dead = {
            description = "dead flow :(",
            damage = 230,
            object = "dead/FlowDED.s3o", --"HunterT.s3o"
            footprintz = 2,
            footprintx = 2,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 36,
            metal = 36,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			featureDead = "flow_heap",
			collisionvolumeoffsets = "0 0 0",
			collisionVolumeScales =  "22 17 35",
			collisionvolumetype = "box",
},
flow_heap = {
            description = "very dead flow :(",
            damage = 46,
            object = "dead/Pieces_Small.s3o",
            footprintz = 2,
            footprintx = 2,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 9,
            metal = 9,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "35 5 35",
			collisionvolumetype = "box",
},
})