return lowerkeys({
  ravager_dead = {
            description = "dead ravager :(",
            damage = 1065,
            object = "dead/RavagerDED.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 98,
            metal = 98,
            hitdensity = 150,
			featureDead  = "ravager_heap",
            world = "All Worlds",
            category = "dedunit",
			collisionVolumeOffsets    =  "0 -4 -5",
			collisionVolumeScales     =  "31 32 54",
			collisionvolumetype = "box",
},
ravager_heap = {
            description = "very dead ravager :(",
            damage = 213,
            object = "dead/Pieces_Big.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 24.5,
            metal = 24.5,
            hitdensity = 150,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "45 7 45",
			collisionvolumetype = "box",
},
})
