return lowerkeys({
  vanguard_dead = {
            description = "dead vanguard :(",
            damage = 1837.5,
            object = "dead/VanguardDED.s3o", 
            footprintz = 4,
            footprintx = 4,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 240,
            metal = 240,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			featureDead = "vanguard_heap",
			collisionvolumeoffsets = "0 0 0",
			collisionVolumeScales =  "55 36 82",
			collisionvolumetype = "box",
},
vanguard_heap = {
            description = "very dead vanguard :(",
            damage = 367.5,
            object = "dead/Pieces_Big.s3o",
            footprintz = 4,
            footprintx = 4,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 60,
            metal = 60,
            hitdensity = 200,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "35 5 35",
			collisionvolumetype = "box",
},
})