return lowerkeys({
  aerialconstructor_dead = {
            description = "dead aerial constructor :(",
            damage = 187.5,
            object = "dead/Aerial ConstructorDED.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 34,
            metal = 34,
            hitdensity = 150,
			featureDead  = "aerialconstructor_heap",
            world = "All Worlds",
            category = "dedunit",
			collisionVolumeOffsets    =  "0 -2 0",
			collisionVolumeScales     =  "20.5 14 41",
			collisionvolumetype = "box",
},
aerialconstructor_heap = {
            description = "very dead aerial constructor :(",
            damage = 37.5,
            object = "dead/Pieces_Big.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 8.5,
            metal = 8.5,
            hitdensity = 150,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "45 7 45",
			collisionvolumetype = "box",
},
})
