return lowerkeys({
 bb_dead = {
            description = "dead Big Bertha D:",
            damage = 2300,
            object = "dead/BBDED.s3o",
            footprintz = 9,
            footprintx = 9,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 2000,
            metal = 2000,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			featureDead = "bb_heap",
			collisionVolumeOffsets    =  "0 25 0",
			collisionVolumeScales     =  "80 292 80",
			collisionvolumetype = "box",
},
bb_heap = {
            description = "very dead Big Bertha D:",
            damage = 560,
            object = "dead/Pieces_BB.s3o",
            footprintz = 9,
            footprintx = 9,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 500,
            metal = 500,
            hitdensity = 150,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "135 15 135",
			collisionvolumetype = "box",
},
})