return lowerkeys({
  catapult_dead = {
            description = "dead catapult :(",
            damage = 460,
            object = "dead/CatapultDED.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 98,
            metal = 98,
            hitdensity = 150,
			featureDead  = "catapult_heap",
            world = "All Worlds",
            category = "dedunit",
			collisionVolumeOffsets    =  "0 0 0",
			collisionVolumeScales     =  "41 26 66",
			collisionvolumetype = "box",
},
catapult_heap = {
            description = "very dead catapult :(",
            damage = 92,
            object = "dead/Pieces_Big.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 24.5,
            metal = 24.5,
            hitdensity = 150,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "45 7 45",
			collisionvolumetype = "box",
},
})
