return lowerkeys({
  gazer_dead = {
            description = "dead gazer :(",
            damage = 400,
            object = "dead/GazerDED.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 300,
            metal = 300,
            hitdensity = 150,
			featureDead  = "gazer_heap",
            world = "All Worlds",
            category = "dedunit",
			collisionVolumeOffsets    =  "0 -4 -5",
			collisionVolumeScales     =  "31.5 33 54",
			collisionvolumetype = "box",
},
gazer_heap = {
            description = "very dead gazer :(",
            damage = 80,
            object = "dead/Pieces_Big.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 75,
            metal = 75,
            hitdensity = 150,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "45 7 45",
			collisionvolumetype = "box",
},
})
