return lowerkeys({
  geothermalgenerator_dead = {
            description = "dead geothermal generator :(",
            damage = 1250,
            object = "dead/Geothermal GeneratorDED.s3o",
            footprintz = 6,
            footprintx = 6,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 240,
            metal = 240,
            hitdensity = 300,
            world = "All Worlds",
            category = "dedunit",
			featureDead = "geothermalgenerator_heap",
			collisionVolumeOffsets    =  "0 10 0",
			collisionVolumeScales     =  "60 68 60",
			collisionvolumetype = "box",
},
geothermalgenerator_heap = {
            description = "very dead geothermal generator :(",
            damage = 250,
            object = "dead/Pieces_ExBig.s3o",
            footprintz = 4,
            footprintx = 4,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 60,
            metal = 60,
            hitdensity = 200,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "60 8 60",
			collisionvolumetype = "box",
},
})