return lowerkeys({
  harpy_dead = {
            description = "dead harpy :(",
            damage = 287.5,
            object = "dead/HarpyDED.s3o", --"HunterT.s3o"
            footprintz = 2,
            footprintx = 2,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 90,
            metal = 90,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			featureDead = "harpy_heap",
			collisionvolumeoffsets = "0 0 0",
			collisionVolumeScales =  "15 10.5 29",
			collisionvolumetype = "box",
},
harpy_heap = {
            description = "very dead harpy :(",
            damage = 57.5,
            object = "dead/Pieces_Small.s3o",
            footprintz = 2,
            footprintx = 2,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 22.5,
            metal = 22.5,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "35 5 35",
			collisionvolumetype = "box",
},
})