return lowerkeys({
  hawk_dead = {
            description = "dead hawk :(",
            damage = 150,
            object = "dead/HawkDED.s3o", --"HunterT.s3o"
            footprintz = 2,
            footprintx = 2,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 40,
            metal = 40,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			featureDead = "hawk_heap",
			collisionvolumeoffsets = "0 0 0",
			collisionVolumeScales =  "15 10.5 29",
			collisionvolumetype = "box",
},
hawk_heap = {
            description = "very dead hawk :(",
            damage = 30,
            object = "dead/Pieces_Small.s3o",
            footprintz = 2,
            footprintx = 2,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 10,
            metal = 10,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "35 5 35",
			collisionvolumetype = "box",
},
})