return lowerkeys({
  hoverfactory_dead = {
            description = "dead hover factory :(",
            damage = 1750,
            object = "dead/Hover FactoryDED.s3o",
            footprintz = 11,
            footprintx = 8,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 300,
            metal = 300,
            hitdensity = 300,
            world = "All Worlds",
            category = "dedunit",
			featureDead = "hoverfactory_heap",
			collisionVolumeOffsets    =  "0 0 -7.5",
			collisionVolumeScales     =  "119 79 174",
			collisionvolumetype = "box",
},
hoverfactory_heap = {
            description = "very dead hover factory  :(",
            damage = 350,
            object = "dead/Pieces_ExBig.s3o",
            footprintz = 4,
            footprintx = 4,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 75,
            metal = 75,
            hitdensity = 200,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "60 8 60",
			collisionvolumetype = "box",
},
})