return lowerkeys({
  hunter_dead = {
            description = "dead hunter :(",
            damage = 160,
            object = "dead/HunterDED.s3o", --"HunterT.s3o"
            footprintz = 2,
            footprintx = 2,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 30,
            metal = 30,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			featureDead = "hunter_heap",
			collisionvolumeoffsets = "0 -5 0",
			collisionvolumescales = "18 17 32",
			collisionvolumetype = "box",
},
hunter_heap = {
            description = "very dead hunter :(",
            damage = 32,
            object = "dead/Pieces_Small.s3o",
            footprintz = 2,
            footprintx = 2,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 7.5,
            metal = 7.5,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "35 5 35",
			collisionvolumetype = "box",
},
})