return lowerkeys({
  lurker_dead = {
            description = "dead lurker :(",
            damage = 1335,
            object = "dead/LurkerDED.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 128,
            metal = 128,
            hitdensity = 150,
			featureDead  = "lurker_heap",
            world = "All Worlds",
            category = "dedunit",
			collisionVolumeOffsets    =  "0 -4 -5",
			collisionVolumeScales     =  "31.5 33 54",
			collisionvolumetype = "box",
},
lurker_heap = {
            description = "very dead lurker :(",
            damage = 267,
            object = "dead/Pieces_Big.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 32,
            metal = 32,
            hitdensity = 150,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "45 7 45",
			collisionvolumetype = "box",
},
})
