return lowerkeys({
  owl_dead = {
            description = "dead owl :(",
            damage = 360,
            object = "dead/OwlDED.s3o", --"HunterT.s3o"
            footprintz = 2,
            footprintx = 2,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 240,
            metal = 240,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			featureDead = "owl_heap",
			collisionvolumeoffsets = "0 0 0",
			collisionVolumeScales  =  "24 12 34",
			collisionvolumetype = "box",
},
owl_heap = {
            description = "very dead owl :(",
            damage = 72,
            object = "dead/Pieces_Small.s3o",
            footprintz = 2,
            footprintx = 2,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 35,
            metal = 35,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "35 5 35",
			collisionvolumetype = "box",
},
})