return lowerkeys({
  picket_dead = {
            description = "dead picket :(",
            damage = 240,
            object = "dead/PicketDED.s3o",
            footprintz = 2,
            footprintx = 2,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 48,
            metal = 48,
			featureDead  = "picket_heap",
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 -5 0",
			collisionvolumescales = "18 17 32",
			collisionvolumetype = "box",
},
picket_heap = {
            description = "very dead picket :(",
            damage = 48,
            object = "dead/Pieces_Small.s3o",
            footprintz = 2,
            footprintx = 2,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 12,
            metal = 12,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "35 5 35",
			collisionvolumetype = "box",
},
})