return lowerkeys({
 pointer_dead = {
            description = "dead pointer :(",
            damage = 200,
            object = "dead/pointerDED.s3o", --"HunterT.s3o"
            footprintz = 2,
            footprintx = 2,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 38,
            metal = 38,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			featureDead = "pointer_heap",
			collisionvolumeoffsets = "0 -5 0",
			collisionvolumescales = "18 17 32",
			collisionvolumetype = "box",
},
pointer_heap = {
            description = "very dead pointer :(",
            damage = 40,
            object = "dead/Pieces_Small.s3o",
            footprintz = 2,
            footprintx = 2,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 9.5,
            metal = 9.5,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "35 5 35",
			collisionvolumetype = "box",
},
})