return lowerkeys({
  skeeter_dead = {
            description = "dead skeeter :(",
            damage = 135,
            object = "dead/SkeeterDED.s3o", --"HunterT.s3o"
            footprintz = 2,
            footprintx = 2,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 30,
            metal = 30,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			featureDead = "skeeter_heap",
			collisionvolumeoffsets = "0 0 0",
			collisionVolumeScales =  "22 17 35",
			collisionvolumetype = "box",
},
skeeter_heap = {
            description = "very dead skeeter :(",
            damage = 27,
            object = "dead/Pieces_Small.s3o",
            footprintz = 2,
            footprintx = 2,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 7.5,
            metal = 7.5,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "35 5 35",
			collisionvolumetype = "box",
},
})