return lowerkeys({
  solarpanel_dead = {
            description = "dead solarpanel :(",
            damage = 250,
            object = "dead/Solar PannelDED.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 30,
            metal = 30,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			featureDead = "solarpanel_heap",
			collisionVolumeOffsets    =  "0 0 0",
			collisionVolumeScales     =  "33 44 33",
			collisionvolumetype = "box",
},
solarpanel_heap = {
            description = "very dead solarpanel :(",
            damage = 25,
            object = "dead/Pieces_Small.s3o",
            footprintz = 2,
            footprintx = 2,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 7.5,
            metal = 7.5,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "35 5 35",
			collisionvolumetype = "box",
},
})