return lowerkeys({
  stormcloud_dead = {
            description = "dead stormcloud :(",
            damage = 1200,
            object = "dead/StormCloudDED.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 320,
            metal = 320,
            hitdensity = 150,
			featureDead  = "stormcloud_heap",
            world = "All Worlds",
            category = "dedunit",
			collisionVolumeOffsets    =  "0 -4 0",
			collisionVolumeScales     =  "31 16 44",
			collisionvolumetype = "box",
},
stormcloud_heap = {
            description = "very dead stormcloud :(",
            damage = 240,
            object = "dead/Pieces_Big.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 80,
            metal = 80,
            hitdensity = 150,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "45 7 45",
			collisionvolumetype = "box",
},
})
