return lowerkeys({
  storage_dead = {
            description = "dead storage :)",
            damage = 250,
            object = "dead/StorageDED.s3o",
            footprintz = 3,
            footprintx = 3,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 40,
            metal = 40,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			featureDead = "storage_heap",
			collisionVolumeOffsets    =  "0 15 0",
			collisionVolumeScales     =  "26 40 26",
			collisionvolumetype = "box",
},
storage_heap = {
            description = "very dead storage :)",
            damage = 32,
            object = "dead/Pieces_Small.s3o",
            footprintz = 2,
            footprintx = 2,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 10,
            metal = 10,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "35 5 35",
			collisionvolumetype = "box",
},
})