return lowerkeys({
  swatter_dead = {
            description = "dead swatter :(",
            damage = 162.5,
            object = "dead/SwatterDED.s3o",
            footprintz = 2,
            footprintx = 2,
            smokeTime = 400,
            reclaimable = true,
            reclaimTime = 72,
            metal = 72,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			featureDead = "flow_heap",
			collisionvolumeoffsets = "0 0 0",
			collisionVolumeScales =  "22 17 35",
			collisionvolumetype = "box",
},
 swatter_heap = {
            description = "very dead  swatter :(",
            damage = 36.5,
            object = "dead/Pieces_Small.s3o",
            footprintz = 2,
            footprintx = 2,
            smokeTime = 100,
            reclaimable = true,
			blocking = false,
            reclaimTime = 18,
            metal = 18,
            hitdensity = 100,
            world = "All Worlds",
            category = "dedunit",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "35 5 35",
			collisionvolumetype = "box",
},
})